export const DOCUMENT = {
  ADD: 'DOCUMENT/ADD',
  ARCHIVE: 'DOCUMENT/ARCHIVE',
  DELETE: 'DOCUMENT/DELETE',

  ROTATE: 'DOCUMENT/ROTATE',
  CROP: 'DOCUMENT/CROP',

  UPLOAD: {
    UPLOAD: 'DOCUMENT/UPLOAD/UPLOAD',
    UPLOAD_PENDING: 'DOCUMENT/UPLOAD/UPLOAD_PENDING',

    LOADING: 'DOCUMENT/UPLOAD/LOADING',
    LOADED: 'DOCUMENT/UPLOAD/LOADED',
    ERROR: 'DOCUMENT/UPLOAD/ERROR',
  }
};

export const SELECT_LOCATION = 'SELECT_LOCATION';
