export const DOCUMENT = {
  ADD: 'DOCUMENT/ADD',
  ARCHIVE: 'DOCUMENT/ARCHIVE',
  DELETE: 'DOCUMENT/DELETE',

  ROTATE: 'DOCUMENT/ROTATE',
  CROP: 'DOCUMENT/CROP',

  UPLOAD: {
    UPLOAD: 'DOCUMENT/UPLOAD/UPLOAD',
    UPLOAD_PENDING: 'DOCUMENT/UPLOAD/UPLOAD_PENDING',

    LOADING: 'DOCUMENT/UPLOAD/LOADING',
    LOADED: 'DOCUMENT/UPLOAD/LOADED',
    ERROR: 'DOCUMENT/UPLOAD/ERROR',
  },

  COMPLETE: 'DOCUMENT/COMPLETE'
};

export const SELECT_LOCATION = 'SELECT_LOCATION';

export const RECEIVE_RECORD = 'RECEIVE_RECORD';

export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const RECEIVE_USER_DETAILS = 'RECEIVE_USER_DETAILS';
