export const SESSION = {
  ADD_SESSION: 'SESSION/ADD_SESSION',

  UPLOAD: {
    START: 'SESSION/UPLOAD/START',

    LOADING: 'SESSION/UPLOAD/LOADING',
    LOADED: 'SESSION/UPLOAD/LOADED',
    ERROR: 'SESSION/UPLOAD/ERROR',
  },
};

export const DOCUMENT = {
  ROTATE: 'DOCUMENT/ROTATE',
  DELETE: 'DOCUMENT/DELETE',
  CROP: 'DOCUMENT/CROP',

  UPLOADED: 'DOCUMENT/UPLOAD/DONE',
};
